---
name: Build Roadmap Docs

on:
  workflow_call:

jobs:
  build:
    name: Build (${{ matrix.project }})
    runs-on: ubuntu-latest
    strategy:
      matrix:
        project:
          - The-IndieDeveloper-Fullstack-Roadmap/CN
          - The-IndieDeveloper-Fullstack-Roadmap/EN
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up build environment
        run: .github/scripts/setup_build_env.sh

      - name: Build documents using Makefile
        run: .github/scripts/build_docs.sh
        env:
          PROJECT: ${{ matrix.project }}

      - name: Prepare artifact name
        run: .github/scripts/prepare_artifact_name.sh
        env:
          PROJECT: ${{ matrix.project }}

      - name: Upload PDF, DOCX, and HTML files to GitHub Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: ${{ env.ARTIFACT_NAME }}
          path: |
            ${{ matrix.project }}
            ${{ matrix.project }}*.pdf
            ${{ matrix.project }}*.docx
            ${{ matrix.project }}*.html
            ${{ matrix.project }}/*.pdf
            ${{ matrix.project }}/*.docx
            ${{ matrix.project }}/*.html
            ${{ matrix.project }}/**/*.pdf
            ${{ matrix.project }}/**/*.docx
            ${{ matrix.project }}/**/*.html
          if-no-files-found: ignore
